export const GENERAL = {
  SET_INPUT: 'SET_INPUT',
  SET_OUTPUT: 'SET_OUTPUT',
  SET_DEFAULT_MULTI_LINE_REGEX: 'SET_DEFAULT_MULTI_LINE_REGEX',
  SET_DEFAULT_MULTI_LINE_COUNT: 'SET_DEFAULT_MULTI_LINE_COUNT',
  SET_DO_REPLACE_BEFORE: 'SET_DO_REPLACE_BEFORE',
  SET_AUTO_TEST_ON_BLUR: 'SET_AUTO_TEST_ON_BLUR',
  SET_MAX_SAMPLE_LENGTH: 'SET_MAX_SAMPLE_LENGTH',
  SET_MAX_SUB_PATTERN_LENGTH: 'SET_MAX_SUB_PATTERN_LENGTH',
  SET_OVERRIDE_DELIMITER: 'SET_OVERRIDE_DELIMITER',
  SET_REGEX_ENGINE: 'SET_REGEX_ENGINE',
  SET_SHOW_WHITESPACE_CHARACTERS: 'SET_SHOW_WHITESPACE_CHARACTERS'
}
