export const REGEX = {
  ADD_NEW_REGEX: 'ADD_NEW_REGEX',
  UPDATE_EXISTING_REGEX: 'UPDATE_EXISTING_REGEX',
  DELETE_REGEX: 'DELETE_REGEX',
  MOVE_EXISTING_REGEX: 'MOVE_EXISTING_REGEX',
  VALIDATE_REGEX: 'VALIDATE_REGEX',
  TEST_REGEX: 'TEST_REGEX',
  INCREMENT_ID: 'INCREMENT_ID'
}

export const UPDATE_REGEX = {
  UPDATE_REGEX_BASIC: 'UPDATE_REGEX_BASIC',
  UPDATE_REGEX_SET_ERROR: 'UPDATE_REGEX_SET_ERROR',
  UPDATE_REGEX_SET_MATCHES: 'UPDATE_REGEX_SET_MATCHES'
}
